//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19._12
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class produktEntities : DbContext
    {
        public produktEntities()
            : base("name=produktEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doljnost> doljnost { get; set; }
        public virtual DbSet<kategoria> kategoria { get; set; }
        public virtual DbSet<magazine> magazine { get; set; }
        public virtual DbSet<postavchik> postavchik { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<sotrudnik> sotrudnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
